language: node_js
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_9962d6011615_key -iv $encrypted_9962d6011615_iv
  -in service-creds.json.enc -out service-creds.json -d
- docker build -t laughingbiscuit/devenv .
script:
- docker run -it laughingbiscuit/devenv /root/lbdk/test.sh
